### ISSUE TITLE
Broken build system

### ISSUE THREAD

**Issue by fabnicol** [flintlib/flintxx#7]
Both the cmake and autotools-based build systems are broken.
The autotools-based build system lacks a crucial configure.ac file that cannot be straightforwardly generated with autoscan (I tried), even after some fairly competent fiddling (I tried too).
The cmake build system runs into errors. Under my MSYS2 MINGW64 platform (with flint 3.1.3-2 installed by pacman) I have the following error log, which point to a missing file "fmpz_reentrant.c":

```
-- Performing Test FLINT_USES_CPUSET - Failed
-- Using FLINT memory manager: reentrant
CMake Error: File C:/rtools44/flintxx-main/src/fmpz/link/fmpz_reentrant.c does not exist.
CMake Error at CMakeLists.txt:216 (configure_file):
  configure_file Problem configuring file
CMake Error: File C:/rtools44/flintxx-main/src/fft_tuning64.in does not exist.
CMake Error at CMakeLists.txt:223 (configure_file):
  configure_file Problem configuring file
CMake Error at CMakeLists.txt:296 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```

**Comment by edgarcosta** [comment]
I believe you reported this to the wrong repo, and wanted to report it on https://github.com/flintlib/flint
